version: 2
updates:
  - package-ecosystem: "maven"
    directory: "./" # Cambia si tu archivo pom.xml est√° en un subdirectorio
    schedule:
      interval: "daily" # Puede ser "daily", "weekly" o "monthly"
